name: abi compatibility check
on:
  pull_request:

env:
  ROS_DISTRO: galactic

jobs:
  abi_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          ROS_REPO: [main, testing]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_REPO: ${{matrix.ROS_REPO}}
          ABICHECK_URL: github:ros-controls/ros2_control#${{ github.base_ref }}
          NOT_TEST_BUILD: true
