name: ROS2 Lint
on:
  pull_request:

jobs:
  ament_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, copyright, lint_cmake]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: ${{ matrix.linter }}
        package-name:
          $PKG_NAME$

  ament_lint_100:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
          linter: [cpplint]
    steps:
    - uses: actions/checkout@v1
    - uses: ros-tooling/setup-ros@v0.2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        distribution: rolling
        linter: cpplint
        arguments: "--linelength=100 --filter=-whitespace/newline"
        package-name:
          ros2_control
