name: Foxy RHEL Binary Build
on:
  pull_request:
    branches:
      - foxy
  push:
    branches:
      - foxy
  schedule:
    # Run every day to detect flakiness and broken dependencies
    - cron: '03 1 * * *'

env:
  # if changing this variable, also change jobs.RHEL.container to match
  ROS_DISTRO: foxy

jobs:
  foxy_rhel_binary:
    name: Foxy RHEL binary build
    runs-on: ubuntu-latest
    container: jaronl/ros:foxy-alma
    steps:
      - uses: actions/checkout@v2
        with:
          path: src/ros2_controllers
      - run: |
          rosdep update
          rosdep install -iy --from-path src/ros2_controllers
          source /opt/ros/$ROS_DISTRO/setup.bash
          colcon build
          colcon test
