name: Galactic - ABI Compatibility Check
on:
  workflow_dispatch:
    branches:
      - galactic
  pull_request:
    branches:
      - galactic

jobs:
  abi_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: galactic
          ROS_REPO: main
          ABICHECK_URL: github:${{ github.repository }}#${{ github.base_ref }}
          NOT_TEST_BUILD: true
