name: Humble - ABI Compatibility Check
on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '.github/workflows/humble-abi-compatibility.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros2_control-not-released.humble.repos'

jobs:
  abi_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: humble
          ROS_REPO: main
          ABICHECK_URL: github:${{ github.repository }}#${{ github.base_ref }}
          NOT_TEST_BUILD: true
