name: Humble Semi-Binary Build - testing
# description: 'Build & test that compiles the main dependencies from source.'

on:
  workflow_dispatch:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble
  schedule:
    # Run every morning to detect flakiness and broken dependencies
    - cron: '33 1 * * *'

jobs:
  semi_binary:
    uses: ./.github/workflows/reusable-industrial-ci-with-cache.yml
    with:
      ros_distro: humble
      ros_repo: testing
      upstream_workspace: ros2_control.humble.repos
      ref_for_scheduled_build: humble
