name: Rolling Downstream Build
# description: 'Build & test downstream packages from source.'
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/jazzy-binary-downstream-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros_controls.jazzy.repos'
  push:
    branches:
      - master
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '**.yaml'
      - '.github/workflows/jazzy-binary-downstream-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'ros_controls.jazzy.repos'

concurrency:
  # cancel previous runs of the same workflow, except for pushes on master branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !startsWith(github.ref, '/refs/heads') }}

jobs:
  build-downstream:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: jazzy
      ros_repo: testing
      ref_for_scheduled_build: master
      not_test_build: true
      downstream_workspace: ros_controls.jazzy.repos
      not_test_downstream: true
