name: Pre-Release Check

on:
  workflow_dispatch:
    inputs:
      ros_distro:
        description: 'Chose ROS distribution'
        required: true
        default: 'rolling'
        type: choice
        options:
        - foxy
        - galactic
        - humble
        - rolling
      branch:
        description: 'Chose branch for distro'
        required: true
        default: 'master'
        type: choice
        options:
        - foxy
        - galactic
        - humble
        - master

jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: industrial_ci
        uses: ros-industrial/industrial_ci@master
        env:
          ROS_DISTRO: ${{ github.event.inputs.ros_distro }}
          PRERELEASE: true
          BASEDIR: ${{ github.workspace }}/.work
